[package]
name = "szpp-code-viewer-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
actix-web = "4"
chrono = { version = "0.4" }
diesel = { version = "1.4", features = ["postgres"] }
