version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8080:8080
  db:
    image: postgres:14
    volumes:
      - $PWD/postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=szpp-judge
    ports:
      - 5432:5432

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      - SWAGGER_URL=
      - SWAGGER_JSON=./spec/openapi.yaml
    ports:
      - 80:8080
    volumes:
      - ./spec:/spec
