openapi: 3.0.3
info:
  title: szpp-judge
  version: 1.0.0

paths:
  /auth/signin:
    post:
      summary: サインイン
      description: サインインをします
      parameters: []
      requestBody: # リクエストボディ
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninPayload'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SigninResponse'
        '401':
          description: 'ID かパスワードが違うよー'
        '500':
          description: 'エラーだよー'

  /users:
    post:
      summary: register user
      description: 新規ユーザーを登録する
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserPayload'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '500':
          description: 'エラーだよー'
  
  /users/{user_id}:
    get:
      summary: get user
      description: ユーザー情報を取得する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: 'ユーザーが見つからない'
        '500':
          description: 'エラーだよー'

components:
  schemas:
    SigninPayload:
      type: object
      required: # 必須フィールド
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    SigninResponse:
      type: object
      properties:
        userResponse:
          $ref: '#/components/schemas/UserResponse'
        token:
          type: string

    UserResponse:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        displayName:
          type: string
        created_at:
          type: string
          format: datetime
        updated_at:
          type: string
          format: datetime
      required:
        - id
        - username
        - created_at

    RegisterUserPayload:
      type: object
      required:
        - username
        - password
        - displayName
      properties:
        username:
          type: string
        password:
          type: string
        displayName:
          type: string
